services:
  - type: web
    name: calc-iq-keras-api
    runtime: python
    plan: free
    # Added uvicorn to ensure FastAPI can run
    buildCommand: pip install -r requirements.txt && pip install gunicorn joblib uvicorn
    # Added the --worker-class to handle FastAPI's async nature
    buildCommand: pip install -r requirements.txt && pip install gunicorn joblib scikit-learn
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: KERAS_BACKEND
        value: tensorflow
